### ISSUE TITLE
Maximum is populated with min value.

### ISSUE THREAD

**Issue by orsonjones** [mulesoft/raml-for-jax-rs#59]
raml with a min and max like this:
```
/endpoint
  get:
    queryParameters:
      id:
        type: integer
        minimum: 1
        maximum: 3
```
results in the min value being used for both min and max annotations.
```
    @Min(1L)
    @Max(1L)
```
