### ISSUE TITLE
Swagger Annotations Not Being Used In RAML Generation From Maven Plugin

### ISSUE THREAD

**Issue by InfoSec812** [mulesoft/raml-for-jax-rs#73]
Sample Application can be found at:

https://github.com/InfoSec812/codepalousa-restlet-raml

Running: mvn clean compile generate-sources and the output RAML has not details about response codes and no links to schemas.

**Comment by petrochenko-pavel-a** [comment]
Thanks a lot for a good reproduction sample.
I will look in it asap.

Regards,
Pavel

**Comment by InfoSec812** [comment]
FYI, running the application is as simple as:

mvn exec:java

The RAML endpoint is mapped to: http://localhost:8180/rest/v1/raml

Thanks!

**Comment by petrochenko-pavel-a** [comment]
I think that the problem is in execution phase which was wrongly pointed to generate-sources in documentation (fixed it)
I used 'process-classes' phase for your sample project ant the things that I got look at least casually correct: https://www.dropbox.com/s/cehyxdudnbrox6t/Archive.zip?dl=0

P.S. Please let me know if it still did not works for you.
Regards,
Pavel

**Comment by InfoSec812** [comment]
Nope, still not working. I have pushed the changes up to my repo, but here's the RAML I am getting:

```
#%RAML 0.8
title: codepalousa-restlet-raml
baseUri: http://example.com
schemas:
  - todo: !include schemas/todo.xsd
  - todo-jsonschema: !include schemas/todo-jsonschema.json
/todo: 
  get: 
  post: 
  /{id}: 
    uriParameters: 
      id: 
        type: integer
    get: 
    put: 
    delete: 
```
