### ISSUE TITLE
JSONSchema2Pojo fails on $ref relative path in RAML-to-JAX-RS

### ISSUE THREAD

**Issue by justjacksonn** [mulesoft/raml-for-jax-rs#93]
Hi all,

So I am not sure if this is truly a bug/problem, or as intended. I have a schema that refers to another schema using $ref. Both schemas are in a /schemas folder. My raml is one dir above, and refers to /schemas/<file>.json. My raml is something like:

```
#%RAML 0.8
---
title: test
baseUri: https://test.company.com
version: v1

schemas:
  - errors: !include schemas/error.json
    address: !include schemas/address.json
    person: !include schemas/person.json

/person:
  displayName: Person
  post:
    body:
      application/json:
        example: |
          { "test":"test2"}
        schema: person
```

When I run the raml2jaxrs (without any schema) everything builds fine.. I am saying this so that you know the build step DOES work. As soon as I add in the schemas: ... and then refer to a schema alias in my raml, the error occurs. Basically without retyping both schemas, they are simple examples found on the net, with a simple person refers to address via "$ref":"address.json".  I validated both schemas and they are fine.

So, when I build, it tells me it can't find the address.json schema file. However, I notice the "temporary" /var/.. location that the jsonschema2pojo seems to use. It gives some odd multi-level deep directory structure. So I CD to that path and sure enough the json files ARE there, but they don't have .json appended to them. Instead, they are using the alias names I list in my RAML file. Frankly, this is all fine, except that the $ref fails UNLESS I change it my my JSON Schema to just use the same alias name in the RAML file, instead of address.json.  so I change the alias to "addr" and addr shows up in the directory. So now my $ref is broken again. Thus, it's forcing me to have my json schema $ref depend on the name of the alias defined in the raml file.

I think this is a bug. I don't think we should have to modify the json schema file to depend on the raml alias name. 

I also tried removing the alias of address: !include schemas/address.json  since I do NOT refer to it in the raml file itself..but the person:person.json alias refers to it in it's json schema. Sure enough, the temporary directory now does not have ANY address or address.json in it, so once again the build does not work because the ref fails.

So.. am I doing something wrong.. or did I discover an ugly bug that needs to get fixed?

In the short term I'll use the work around that "works".
